### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by dreamwhisper**
Adds a default codeowners file.

### CODE REVIEW

**Review by johnstonphilip — APPROVED** [review]

**Comment by kienstra** [comment]
Hm, do you also [see this](https://github.com/studiopress/.github/pull/4/files#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7R2)?

Screenshot 2023-02-22 at 3 39 39 PM

**Comment by kienstra** [comment]
Actually, that should be resolved, per our conversation. All good! 😄

**Comment by dreamwhisper** [comment]
For reference, the team has to have access to the repo. Otherwise, it throws the syntax error.

**Comment by dreamwhisper** [comment]
In other words, added here:

Screen Shot 2023-02-22 at 4 59 24 PM

**Comment by kienstra** [comment]
Good find!

**Pull request merged**
